#92 Bump smallrye-config to 2.12.1
i-Cell-Mobilsoft-Open-Source/roaster pull request #104
Opened 2022-12-08 10:39 UTC by gabor-balazs

2022-12-08 11:46 UTC, rombow requested changes

2022-12-08 11:46 UTC, rombow commented on roaster-bom/pom.xml
> +		<version.io.smallrye.config>2.12.1</version.io.smallrye.config>
2.13.0 mar a legujabb + leccives valamit irjal a migracios doksiba

2022-12-08 13:02 UTC, rombow approved these changes

2022-12-08 13:05 UTC, martin-nagy approved these changes

2022-12-09 06:40 UTC, czenczl approved these changes

2022-12-09 09:52 UTC, merged