#18 -  Az EntityManagerProducer ne állítson elő defaultPU-val EntityManagerFactory-t, ha nem szükséges
i-Cell-Mobilsoft-Open-Source/roaster pull request #19
Opened 2021-01-07 08:21 UTC by bcsabi

EntityManagerProducer osztályban injectálás helyett, az EntityManagerFactory előállítása a produceDefaultEntityManager() metódusban

2021-01-07 08:28 UTC, rombow approved these changes

2021-01-07 08:28 UTC, rombow requested changes
meg a migracios doksit lefelejtetted

2021-01-07 08:50 UTC, czenczl approved these changes

2021-01-08 00:30 UTC, bucherarnold approved these changes

2021-01-08 07:59 UTC, czenczl approved these changes

2021-01-12 13:34 UTC, rombow approved these changes

2021-02-22 07:40 UTC, vasizs approved these changes

2021-02-22 07:47 UTC, merged