#28 putJson és putXml felvétele a ResponseProcessorba
i-Cell-Mobilsoft-Open-Source/roaster pull request #29
Opened 2021-06-09 10:09 UTC by CrazyMacro

2021-06-09 10:17 UTC, rombow requested changes
A mikgracios dokumentumba leccives ird bele mi a valtozas

2021-06-15 11:59 UTC, CrazyMacro commented
> A migracios dokumentumba leccives ird bele mi a valtozas

frissítve

2021-06-15 15:07 UTC, petrenyi-mark submitted a review, later dismissed

2021-06-16 07:44 UTC, bucherarnold submitted a review, later dismissed

2021-06-16 07:47 UTC, rombow submitted a review, later dismissed

2021-06-28 06:16 UTC, martin-nagy commented on roaster-restassured/src/main/java/hu/icellmobilsoft/roaster/restassured/response/ResponseProcessor.java
> +     *            response class The path parameters. See {@link RequestSpecification#post(String, Object...)} pathParams.
Itt a post-ra mutat a link

2021-07-05 10:07 UTC, rombow approved these changes

2021-07-05 10:11 UTC, petrenyi-mark approved these changes

2021-07-05 10:19 UTC, rombow approved these changes

2021-07-05 10:28 UTC, martin-nagy approved these changes

2021-07-05 10:31 UTC, vasizs approved these changes

2021-07-05 10:49 UTC, merged